### ISSUE TITLE
Suggestion for organizing the a lot of LOC yaml file

### ISSUE THREAD

**Issue by RTae** [GoogleCloudPlatform/workflows-samples#176]
Right now I implement a system with GCP workflow but I have some problem about how to organizing the yaml file which have a lot of LOC. However, in some platform fix this problem by using multiple file such as gitlab CICD that you can import another yaml file into the another one.

Does anyone have any suggestion ?

**Comment by rogerthatdev** [comment]
Hi!

Thanks for your question! A solution to your problem is described in [this blog post](https://cloud.google.com/blog/topics/developers-practitioners/deploying-multi-yaml-workflows-definitions-terraform) written by a colleague of mine.  

In short, while Workflows only supports a single workflow definition file, if you use Terraform to manage your workflows you can use a combination of its [join function](https://developer.hashicorp.com/terraform/language/functions/join) and [templatefile function](https://developer.hashicorp.com/terraform/language/functions/templatefile) to combine multiple definition files.  

All of the yaml files do end up getting merged and deployed as a single yaml to workflows, but it does simplify the management of the subworkflows that you might have.

**Comment by RTae** [comment]
@rogerthatdev 
Thank you for your advice

What about in the dev environment? from your suggestion it is about a production, but in the dev environment is a huge problem that we need to merge all file to test run, so it became chunky.
